// import { makeStyles } from "@mui/styles";

// export const useStyles16 = makeStyles({
//   sidebar: {
//     width: "13%",
//     height: "100vh",
//     backgroundColor: "#11101d",
//     display: "flex",
//     flexDirection: "column",
//     alignItems: "center",
//     position: "fixed",
//     justifyContent: "space-between",
//     padding: "10px 0",
//   },
//   topSection: {
//     width: "100%",
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   profileImage: {
//     width: "30px",
//     height: "30px",
//     borderRadius: "0%",
//   },
//   menuSection: {
//     width: "100%",
//     display: "flex",
//     flexDirection: "column",
//     alignItems: "center",
//     flexGrow: 1,
//     justifyContent: "center",
//   },
//   menuItem: {
//     position: "relative",
//     width: "100%",
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//     padding: "20px 0",
//     cursor: "pointer",
//     color: "#fff",
//     border: "none",
//     background: "none",
//     "&:hover $tooltip": {
//       display: "block",
//     },
//     "& i": {
//       fontSize: "24px",
//     },
//   },
//   tooltip: {
//     display: "none",
//     position: "absolute",
//     left: "110%",
//     backgroundColor: "#fff",
//     color: "#11101d",
//     padding: "5px 10px",
//     borderRadius: "5px",
//     boxShadow: "0 0 5px rgba(0, 0, 0, 0.2)",
//     whiteSpace: "nowrap",
//     zIndex: 1,
//   },
//   bottomSection: {
//     width: "100%",
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//     paddingBottom:"10px",
//     paddingRight:"5px",
//   },
// });
